sudo: required
language: python
cache: pip

install:
  - pip install awscli

before_script:
  - aws configure set aws_access_key_id ${AWS_ACCESS_KEY_ID}
  - aws configure set aws_secret_access_key ${AWS_SECRET_ACCESS_KEY}
  - docker login -u AWS -p $(aws --region us-east-2 ecr get-login-password) ${ECR_REGISTRY}

script:
  - docker build . --target build

deploy:
  skip_cleanup: true
  provider: script
  script: ./build_push_image.sh
  on:
    branch: main